/* jshint esnext: true */
// This method generates a list of primes and demonstrates the
// use of ES6 generators.  By using generators, we can consume
// the primes generated by this method one at a time inside a
// for of loop.
//
// https://github.com/google/traceur-compiler/wiki/LanguageFeatures#generators
export function* computePrimes(maxInclusive){
  primes: for(var target = 2; target <= maxInclusive; target ++ ) {
    for(var spoiler = 2; spoiler < target; spoiler ++) {
      if(Math.floor(target/spoiler)===target/spoiler) {
        continue primes;
      }
    }
    yield target;
  }
}
